In [ ]:
import pandas as pd
import numpy as np
import math
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/AnjulaMehto/Sampling_Assignment/main/Creditcard_data.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,575,-0.572263,0.731748,1.541254,0.150506,1.108974,0.372152,1.084879,-0.146329,-0.274447,...,-0.143508,-0.107582,-0.418263,-0.731029,0.877525,-0.364150,-0.177509,-0.256545,26.72,0
768,579,-1.296845,-0.511605,2.404726,-0.310762,-0.319551,-0.542842,-0.173310,0.260423,-1.202688,...,-0.071270,-0.161175,0.088496,0.285390,0.281069,-0.370130,0.043410,0.092318,80.00,0
769,579,1.214170,0.210481,0.484651,0.479768,-0.261955,-0.527039,0.021782,-0.106888,-0.037631,...,-0.224292,-0.594609,0.159877,0.091873,0.140964,0.227406,-0.017389,0.016030,5.98,0
770,580,1.267030,-0.071114,0.037680,0.512683,0.242392,0.705212,-0.226582,0.109483,0.657565,...,-0.164468,-0.177225,-0.222918,-1.245505,0.678360,0.525059,0.002920,-0.003333,12.36,0
771,581,1.153758,0.132273,0.382969,1.405063,-0.224287,-0.197295,0.020653,0.029260,0.412254,...,-0.107809,-0.125231,-0.057041,0.073082,0.633977,-0.310685,0.033590,0.015250,13.79,0

In [ ]:
print((df['Class']==0).sum())
print((df['Class']==1).sum())
print(df.shape)

763
9
(772, 31)

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
sm = SMOTE(random_state=42)
x1, y1 = sm.fit_resample(x, y)

In [ ]:
print((y1==0).sum())
print((y1==1).sum())

763
763

In [ ]:
def models(df1):
  
  X_train, X_test, y_train, y_test = train_test_split(
    df1.iloc[:,0:-1], df1.iloc[:,-1], test_size=0.1, random_state=42)
  acc=[]

  #decision tree
  clf = tree.DecisionTreeClassifier()
  clf.fit(X_train, y_train)
  pdt=clf.predict(X_test)
  z=accuracy_score(y_test, pdt)
  acc.append(z)

  #random forest
  clf1 = RandomForestClassifier(n_estimators = 100) 
  clf1.fit(X_train,y_train)
  pdr=clf1.predict(X_test)
  z=accuracy_score(y_test,pdr)
  acc.append(z)

  #svm
  clf2 = svm.SVC(kernel='linear')
  clf2.fit(X_train,y_train)
  pds=clf2.predict(X_test)
  z=accuracy_score(y_test, pds)
  acc.append(z)

  #knn
  clf3 = KNeighborsClassifier(n_neighbors = 15)
  clf3.fit(X_train,y_train)
  pdk=clf3.predict(X_test)
  z=accuracy_score(y_test,pdk)
  acc.append(z)

  #lr
  clf4 = LogisticRegression(random_state=0,max_iter=1000)
  clf4.fit(X_train,y_train)
  pdl=clf4.predict(X_test)
  z=accuracy_score(y_test, pdl)
  acc.append(z)

  return acc

In [ ]:
ndf=pd.DataFrame(x1)
ndf['Class']=y1
ndf

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.620000,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.690000,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.660000,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.500000,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.990000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521,233,-0.143424,0.517932,0.731111,0.129628,0.854012,0.001878,0.422518,0.075371,-0.127180,...,-0.086502,-0.238275,0.062436,-0.985098,-1.003529,-0.039215,0.158937,0.153083,0.992166,1
1522,288,-0.314860,0.491771,0.951783,0.141217,0.878564,-0.195386,0.522255,0.024692,-0.130443,...,-0.053105,-0.124739,-0.007566,-0.685670,-0.698822,-0.129806,0.101392,0.092159,0.993877,1
1523,465,-2.161259,-0.202359,0.365042,2.613566,0.923353,-0.447669,-2.330450,1.099415,-0.963817,...,0.471321,0.560975,-0.095592,-0.250085,-0.083285,0.508771,0.074280,-0.156735,0.726598,1
1524,516,-2.181198,-1.036044,1.153616,0.342333,1.069585,-0.553986,0.288244,0.069938,-0.076396,...,0.105787,0.020804,0.293645,-0.256581,-0.126499,0.109506,-0.313804,-0.241336,180.086978,1
1525,365,-1.073464,-1.133695,1.566331,0.681840,1.729351,0.441039,-1.034480,0.498312,0.475220,...,0.176062,0.490331,0.232206,-1.083672,-0.742202,0.509854,0.034676,0.008290,1.272031,1

In [ ]:
np.random.seed(0)
sample_size = 308
random_sample = ndf.sample(n=sample_size, random_state=0)
a1=models(random_sample.copy())
print(a1)

[0.967741935483871, 1.0, 0.8709677419354839, 0.5483870967741935, 0.8064516129032258]

In [ ]:
n = len(ndf)
k = int(math.sqrt(n))
sample = ndf.iloc[::k]
a2=models(sample.copy())
print(a2)

[1.0, 1.0, 0.5, 0.25, 0.5]

In [ ]:
ssdf=ndf.groupby('Class', group_keys=False).apply(lambda x: x.sample(n=383))
a3=models(ssdf.copy())
print(a3)

[0.974025974025974, 0.987012987012987, 0.8961038961038961, 0.7532467532467533, 0.8831168831168831]

In [ ]:
clusters = np.random.choice(np.arange(0,2), size=2, replace=False)
cluster_sample = ndf[ndf['Class'].isin(clusters)]
a4=models(cluster_sample.copy())
print(a4)

[0.9803921568627451, 0.9934640522875817, 0.9411764705882353, 0.8431372549019608, 0.934640522875817]

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
dict={
    "random sampling":a1,
    "systematic sampling":a2,
    "stratified sampling":a3,
    "cluster sampling":a4
}

fdf=pd.DataFrame(dict,index=["Decision Tree","Random Forest","SVM", "KNN",
                             "Logistic Regression"])
fdf

,random sampling,systematic sampling,stratified sampling,cluster sampling
Decision Tree,0.967742,1.00,0.974026,0.980392
Random Forest,1.000000,1.00,0.987013,0.993464
SVM,0.870968,0.50,0.896104,0.941176
KNN,0.548387,0.25,0.753247,0.843137
Logistic Regression,0.806452,0.50,0.883117,0.934641